# Playbook to smoke test standup module, to verify a new installation or test code changes in the module.
# Needs verify-cluster-checks.yml in the same directory where this playbook is run from,
#or, adjust the paths suitably.
---
- name: standup-test
  hosts: all
  become: yes
  tasks:
      - name: Setup test bed - install MySQL
        yum: name=mariadb-server,mariadb

      - name: Setup test bed - install Apache
        yum: name=httpd

      - name: Setup test bed - start mysql
        service: name=mariadb state=started

      - name: Setup test bed - start Apache
        service: name=httpd state=started

      - name: Copy checks input file to remote host
        copy: 
           src: verify-cluster-checks-centos.yml 
           dest: /tmp/verify-cluster-checks.yml 

      - name: Run only db and web related checks 
        standup: 
           checks_file_path: /tmp/verify-cluster-checks.yml 
           roles: web,db
        register: output_web_mysql
        ignore_errors: true
      
      - debug: var=output_web_mysql

      - name: Run all the checks 
        standup: 
           checks_file_path: /tmp/verify-cluster-checks.yml
        register: output_all
        ignore_errors: true
          
      - debug: var=output_all

      - name: Stop mysql service so following task will run heal step
        service: name=mariadb state=stopped

      - name: Run db and web related checks with heal option enabled
        standup: 
           heal_state: true
           checks_file_path: /tmp/verify-cluster-checks.yml 
           roles: web,db
        register: output_heal
        ignore_errors: true

      - debug: var=output_heal

